sudo: true
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
    fast_finish: true

branches:
  only:
    - /^8.x/

before_install:
  - export SCRIPT_DIR=$TRAVIS_BUILD_DIR/.scripts
  - export DRUPAL_DIR=/opt/drupal

install:
  - $SCRIPT_DIR/travis_setup.sh
  - cd $DRUPAL_DIR; composer config repositories.local path "$TRAVIS_BUILD_DIR"
  - composer require "islandora/islandora:dev-$TRAVIS_COMMIT as dev-8.x-1.x" --prefer-source
  - cd web; drush en -y islandora

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info $TRAVIS_BUILD_DIR
  - phpcpd --names *.module,*.inc,*.test,*.php $TRAVIS_BUILD_DIR
  - php core/scripts/run-tests.sh --verbose --php `which php` islandora

notifications:
  irc:
    channels:
      - "irc.freenode.org#islandora"
    on_success: change
    on_failure: always
    skip_join: true
